better ui

diff --git a/.github/workflows/intergrated.yml b/.github/workflows/intergrated.yml
--- a/.github/workflows/intergrated.yml
+++ b/.github/workflows/intergrated.yml
@@ -7,7 +7,7 @@ on:
   push:
     branches: 
       - master
-      # - all
+      - all
   pull_request:
     branches: [ "master" ]
 
@@ -100,39 +100,54 @@ jobs:
         - name: Get Name File from VM
           run: rsync -avz -e "ssh -p 22"  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/metaverseops/report_url.txt ./
 
-        - name: Get Test Result from VM
-          run: rsync -avz -e "ssh -p 22"  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$(cat report_url.txt) ./black_box.html
-
 
         # for sending emails
         - name: Install Node.js dependencies
           run: npm ci
         
+        - name: download requirement for white box
+          run: git clone https://github.com/ginalined/white_box_test_html.git
+
+        - name: Get Test Result from VM
+          run: rsync -avz -e "ssh -p 22"  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$(cat report_url.txt) ./white_box_test_html/test_result.html
+      
+        - uses: actions/setup-python@v4
+          with:
+            python-version: '3.9'
+            cache: 'pip' # caching pip dependencies
+        
+        - name: download parser
+        - run: pip install beautifulsoup4
+
+        - name: build white box structure
+        - run: python white_box_test_html/white_struct.py   
+          
         - id: files
           uses: jitterbit/get-changed-files@v1
         - run: |
-              echo "<!DOCTYPE html><html><body>" > white_box.html
-              echo "<h2>Eslint testing Result</h2>" >> white_box.html
               count=$((0))
               for changed_file in ${{ steps.files.outputs.added }}; 
               do
               if [[ $changed_file == *.js ]]
               then
-                echo "<h5> $changed_file <h5>" >> white_box.html
-                npx eslint $changed_file >> white_box.html || true
-                echo "<br>" >> white_box.html || true
+                echo "$changed_file" > error.txt
+                npx eslint $changed_file >> error.txt || true
+                python white_box_test_html/insert_white_box.py
                 count=$((count + 1))
               fi
               done
 
               if [[ $count == 0 ]]
               then
-                echo "<div><h5> No Eslint Error! <h5></div>" >> white_box.html
+                echo "No Error" > error.txt
+                python insert_white_box.py
               fi
-              echo "<br><br><br></body></html>" >> white_box.html
+           
 
-        - name: Concat Html
-          run: cat white_box.html black_box.html > test_result.html
+
+
+        # - name: Concat Html
+        #   run: cat white_box.html black_box.html > test_result.html
 
         - name: Send mail
           uses: dawidd6/action-send-mail@v3
@@ -150,6 +165,6 @@ jobs:
             # Required sender full name (address can be skipped):
             from: Metaverse CICD Developer # <user@example.com>
             # Optional plain body:
-            html_body: file://${{ github.workspace }}/test_result.html
+            html_body: file://${{ github.workspace }}/white_box_test_html/test_changed.html
             ignore_cert: true
 
